Remove an error msg from graceful-stop of puppet-zuul
Sometimes the graceful-stop will complain there is no pidfile,
and then cannot get the pid to stop.

For more detailed info, please refer to the paste URL which is
a same issue about nodepool:
http://paste.openstack.org/show/477599/

Change-Id: Ic83826a4c96a150c00edc0e9ecbb588fdc62ab30

diff --git a/files/zuul.init b/files/zuul.init
--- a/files/zuul.init
+++ b/files/zuul.init
@@ -34,6 +34,17 @@ USER=zuul
 . /lib/lsb/init-functions
 
 #
+# Get the status of the daemon process
+#
+get_daemon_status()
+{
+	# Return
+	#   0  if daemon is running
+	#   !0 if daemon is not running
+	status_of_proc "$DAEMON" "$NAME" >/dev/null 2>&1 || return $?
+}
+
+#
 # Function that starts the daemon/service
 #
 do_start()
@@ -78,21 +89,26 @@ do_stop()
 #
 do_graceful_stop()
 {
-	PID=`cat $PIDFILE`
-	kill -USR1 $PID
+	get_daemon_status
+	if [ $? -eq 0 ]; then
+		PID=`pidof -o %PPID -x $DAEMON`
+		kill -USR1 $PID
 
-	# wait until really stopped
-	if [ -n "${PID:-}" ]; then
-		i=0
-		while kill -0 "${PID:-}" 2> /dev/null;  do
-			if [ $i -eq '0' ]; then
-				echo -n " ... waiting "
-			else
-				echo -n "."
-			fi
-			i=$(($i+1))
-			sleep 1
-		done
+		# wait until really stopped
+		if [ -n "${PID:-}" ]; then
+			i=0
+			while kill -0 "${PID:-}" 2> /dev/null;  do
+				if [ $i -eq '0' ]; then
+					echo -n " ... waiting "
+				else
+					echo -n "."
+				fi
+				i=$(($i+1))
+				sleep 1
+			done
+		fi
+	else
+		echo "Unable to find nodepool to stop"
 	fi
 
 	rm -f /var/run/$NAME/*
